<a href="https://colab.research.google.com/github/MSebastian2021/Artificial_Neural_Networks_Tests/blob/main/Regression_Housing_mine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from sklearn.datasets import load_boston

boston_dataset = load_boston()
boston_dataset

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.
    :func:`~sklearn.datasets.fetch_california_housing`) and the Ames housing
    dataset. You can load the datasets as follows::

        from sklearn.datasets import fetch_california_housing
        housing = fetch_california_housing()

    for the California housing dataset and::

        from sklearn.datasets import fetch_openml
        housing = fetch_openml(name="house_prices", as_frame=True)

    for the Ames housing dataset.

  warnings.warn(msg, category=FutureWarning)

{'DESCR': ".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000\n        - PTRATIO  pupil-teacher ratio by town\n        - B        1000(Bk - 0.63)^2 where Bk is the proportion of black people by town\n        - LSTAT    % lower status of the population\n        - MEDV     Median value of owner-occupied homes in $1000's\n\n    :Missing Attribute Values: None\n\n    :Creator: Harrison, D. and Rubinfeld, D.L.\n\nThis is a copy of UCI ML housing dataset.\nhttps://archive.ics.uci.edu/ml/machine-learning-databases/housing/\n\n\nThis dataset was taken from the StatLib library which is maintained at Carnegie Mellon University.\n\nThe Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic\nprices and the demand for clean air', J. Environ. Economics & Management,\nvol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics\n...', Wiley, 1980.   N.B. Various transformations are used in the table on\npages 244-261 of the latter.\n\nThe Boston house-price data has been used in many machine learning papers that address regression\nproblems.   \n     \n.. topic:: References\n\n   - Belsley, Kuh & Welsch, 'Regression diagnostics: Identifying Influential Data and Sources of Collinearity', Wiley, 1980. 244-261.\n   - Quinlan,R. (1993). Combining Instance-Based and Model-Based Learning. In Proceedings on the Tenth International Conference of Machine Learning, 236-243, University of Massachusetts, Amherst. Morgan Kaufmann.\n",
 'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'data_module': 'sklearn.datasets.data',
 'feature_names': array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
        'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7'),
 'filename': 'boston_house_prices.csv',
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
        19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
        20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
        23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
        33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
        21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
        20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
        23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
        15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21.5, 19.6, 15.3, 19.4,
        17. , 15.6, 13.1, 41.3, 24.3, 23.3, 27. , 50. , 50. , 50. , 22.7,
        25. , 50. , 23.8, 23.8, 22.3, 17.4, 19.1, 23.1, 23.6, 22.6, 29.4,
        23.2, 24.6, 29.9, 37.2, 39.8, 36.2, 37.9, 32.5, 26.4, 29.6, 50. ,
        32. , 29.8, 34.9, 37. , 30.5, 36.4, 31.1, 29.1, 50. , 33.3, 30.3,
        34.6, 34.9, 32.9, 24.1, 42.3, 48.5, 50. , 22.6, 24.4, 22.5, 24.4,
        20. , 21.7, 19.3, 22.4, 28.1, 23.7, 25. , 23.3, 28.7, 21.5, 23. ,
        26.7, 21.7, 27.5, 30.1, 44.8, 50. , 37.6, 31.6, 46.7, 31.5, 24.3,
        31.7, 41.7, 48.3, 29. , 24. , 25.1, 31.5, 23.7, 23.3, 22. , 20.1,
        22.2, 23.7, 17.6, 18.5, 24.3, 20.5, 24.5, 26.2, 24.4, 24.8, 29.6,
        42.8, 21.9, 20.9, 44. , 50. , 36. , 30.1, 33.8, 43.1, 48.8, 31. ,
        36.5, 22.8, 30.7, 50. , 43.5, 20.7, 21.1, 25.2, 24.4, 35.2, 32.4,
        32. , 33.2, 33.1, 29.1, 35.1, 45.4, 35.4, 46. , 50. , 32.2, 22. ,
        20.1, 23.2, 22.3, 24.8, 28.5, 37.3, 27.9, 23.9, 21.7, 28.6, 27.1,
        20.3, 22.5, 29. , 24.8, 22. , 26.4, 33.1, 36.1, 28.4, 33.4, 28.2,
        22.8, 20.3, 16.1, 22.1, 19.4, 21.6, 23.8, 16.2, 17.8, 19.8, 23.1,
        21. , 23.8, 23.1, 20.4, 18.5, 25. , 24.6, 23. , 22.2, 19.3, 22.6,
        19.8, 17.1, 19.4, 22.2, 20.7, 21.1, 19.5, 18.5, 20.6, 19. , 18.7,
        32.7, 16.5, 23.9, 31.2, 17.5, 17.2, 23.1, 24.5, 26.6, 22.9, 24.1,
        18.6, 30.1, 18.2, 20.6, 17.8, 21.7, 22.7, 22.6, 25. , 19.9, 20.8,
        16.8, 21.9, 27.5, 21.9, 23.1, 50. , 50. , 50. , 50. , 50. , 13.8,
        13.8, 15. , 13.9, 13.3, 13.1, 10.2, 10.4, 10.9, 11.3, 12.3,  8.8,
         7.2, 10.5,  7.4, 10.2, 11.5, 15.1, 23.2,  9.7, 13.8, 12.7, 13.1,
        12.5,  8.5,  5. ,  6.3,  5.6,  7.2, 12.1,  8.3,  8.5,  5. , 11.9,
        27.9, 17.2, 27.5, 15. , 17.2, 17.9, 16.3,  7. ,  7.2,  7.5, 10.4,
         8.8,  8.4, 16.7, 14.2, 20.8, 13.4, 11.7,  8.3, 10.2, 10.9, 11. ,
         9.5, 14.5, 14.1, 16.1, 14.3, 11.7, 13.4,  9.6,  8.7,  8.4, 12.8,
        10.5, 17.1, 18.4, 15.4, 10.8, 11.8, 14.9, 12.6, 14.1, 13. , 13.4,
        15.2, 16.1, 17.8, 14.9, 14.1, 12.7, 13.5, 14.9, 20. , 16.4, 17.7,
        19.5, 20.2, 21.4, 19.9, 19. , 19.1, 19.1, 20.1, 19.9, 19.6, 23.2,
        29.8, 13.8, 13.3, 16.7, 12. , 14.6, 21.4, 23. , 23.7, 25. , 21.8,
        20.6, 21.2, 19.1, 20.6, 15.2,  7. ,  8.1, 13.6, 20.1, 21.8, 24.5,
        23.1, 19.7, 18.3, 21.2, 17.5, 16.8, 22.4, 20.6, 23.9, 22. , 11.9])}

In [ ]:
print('data is: {}'.format(boston_dataset.data))
print('independent variable names are: {}'.format(boston_dataset.feature_names))
print('labels or prices: {}'.format(boston_dataset.target))

data is: [[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
independent variable names are: ['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']
labels or prices: [24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 30.3 34.6 34.9 32.9 24.1 42.3 48.5 50.  22.6 24.4 22.5 24.4 20.
 21.7 19.3 22.4 28.1 23.7 25.  23.3 28.7 21.5 23.  26.7 21.7 27.5 30.1
 44.8 50.  37.6 31.6 46.7 31.5 24.3 31.7 41.7 48.3 29.  24.  25.1 31.5
 23.7 23.3 22.  20.1 22.2 23.7 17.6 18.5 24.3 20.5 24.5 26.2 24.4 24.8
 29.6 42.8 21.9 20.9 44.  50.  36.  30.1 33.8 43.1 48.8 31.  36.5 22.8
 30.7 50.  43.5 20.7 21.1 25.2 24.4 35.2 32.4 32.  33.2 33.1 29.1 35.1
 45.4 35.4 46.  50.  32.2 22.  20.1 23.2 22.3 24.8 28.5 37.3 27.9 23.9
 21.7 28.6 27.1 20.3 22.5 29.  24.8 22.  26.4 33.1 36.1 28.4 33.4 28.2
 22.8 20.3 16.1 22.1 19.4 21.6 23.8 16.2 17.8 19.8 23.1 21.  23.8 23.1
 20.4 18.5 25.  24.6 23.  22.2 19.3 22.6 19.8 17.1 19.4 22.2 20.7 21.1
 19.5 18.5 20.6 19.  18.7 32.7 16.5 23.9 31.2 17.5 17.2 23.1 24.5 26.6
 22.9 24.1 18.6 30.1 18.2 20.6 17.8 21.7 22.7 22.6 25.  19.9 20.8 16.8
 21.9 27.5 21.9 23.1 50.  50.  50.  50.  50.  13.8 13.8 15.  13.9 13.3
 13.1 10.2 10.4 10.9 11.3 12.3  8.8  7.2 10.5  7.4 10.2 11.5 15.1 23.2
  9.7 13.8 12.7 13.1 12.5  8.5  5.   6.3  5.6  7.2 12.1  8.3  8.5  5.
 11.9 27.9 17.2 27.5 15.  17.2 17.9 16.3  7.   7.2  7.5 10.4  8.8  8.4
 16.7 14.2 20.8 13.4 11.7  8.3 10.2 10.9 11.   9.5 14.5 14.1 16.1 14.3
 11.7 13.4  9.6  8.7  8.4 12.8 10.5 17.1 18.4 15.4 10.8 11.8 14.9 12.6
 14.1 13.  13.4 15.2 16.1 17.8 14.9 14.1 12.7 13.5 14.9 20.  16.4 17.7
 19.5 20.2 21.4 19.9 19.  19.1 19.1 20.1 19.9 19.6 23.2 29.8 13.8 13.3
 16.7 12.  14.6 21.4 23.  23.7 25.  21.8 20.6 21.2 19.1 20.6 15.2  7.
  8.1 13.6 20.1 21.8 24.5 23.1 19.7 18.3 21.2 17.5 16.8 22.4 20.6 23.9
 22.  11.9]

In [ ]:
df = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names)
df['Price'] = boston_dataset.target
df.head(n=10)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3.0,222.0,18.7,394.12,5.21,28.7
6,0.08829,12.5,7.87,0.0,0.524,6.012,66.6,5.5605,5.0,311.0,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0.0,0.524,6.172,96.1,5.9505,5.0,311.0,15.2,396.90,19.15,27.1
8,0.21124,12.5,7.87,0.0,0.524,5.631,100.0,6.0821,5.0,311.0,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0.0,0.524,6.004,85.9,6.5921,5.0,311.0,15.2,386.71,17.10,18.9

In [ ]:
df.describe(include='all')

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [ ]:
x = df.loc[:, df.columns != 'Price']
y = df.loc[:, df.columns == 'Price']

In [ ]:
# Split the data into training and test set (20% for the test set)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y,test_size = 0.2, random_state = 123) # We use random_state to make sure splitting contains the same data each time.

In [ ]:
#Standardise the data (x_standardised = (x - x_mean)/std_dev)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test) #note that we use the scale set from the training set to transform the test set
df = pd.DataFrame(X_train)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,-0.401149,3.653859,-1.226095,-0.245698,-1.199016,2.231987,-1.278274,0.623686,-0.636934,-1.095990,-1.753696,0.388482,-1.266398
1,0.702723,-0.486534,0.995482,-0.245698,1.587329,0.176596,1.008537,-0.806000,1.675027,1.530409,0.808919,0.313998,0.940407
2,-0.389296,-0.486534,-1.028718,-0.245698,-0.391243,-1.008059,0.697674,-0.557330,-0.521336,-0.668160,-0.868429,0.433478,0.261930
3,-0.391244,-0.486534,-1.195840,-0.245698,-0.950404,0.487675,-0.399281,-0.136278,-0.868130,-0.787002,-0.216127,0.008419,-0.867459
4,-0.403599,2.782197,-1.035921,-0.245698,-1.251491,-0.559197,-0.763742,1.654751,-0.752532,0.359819,1.228256,0.433478,0.277382
...,...,...,...,...,...,...,...,...,...,...,...,...,...
399,-0.395821,-0.486534,-1.195840,-0.245698,-0.950404,2.185112,-1.146068,-0.136278,-0.868130,-0.787002,-0.216127,0.396673,-1.300111
400,0.149849,-0.486534,0.995482,-0.245698,0.503416,0.287391,0.879904,-0.693513,1.675027,1.530409,0.808919,0.425942,0.822411
401,-0.365143,-0.486534,-0.548961,-0.245698,-0.537485,-0.341868,-0.681559,0.437816,-0.521336,-0.721639,0.529361,0.433478,-0.719964
402,0.641524,-0.486534,0.995482,-0.245698,1.243229,-1.059195,1.108585,-1.032987,1.675027,1.530409,0.808919,0.433478,1.513530
403,0.113900,-0.486534,0.995482,-0.245698,1.398074,-3.864583,0.676235,-1.017626,1.675027,1.530409,0.808919,-0.027403,-0.801438

Architecture based on two Dense layers, the first with 128 and the second with 64 neurons, both using a ReLU (Rectified Linear Unit) activation function. 

A dense layer with a linear activation will be used as output layer.

In [ ]:
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential()

#add first layer and first hidden layer, units = number of nodes / neurons
model.add(tf.keras.layers.Dense(units=128, activation='relu'))

#add second hidden layer
model.add(tf.keras.layers.Dense(units=64, activation='relu'))

In [ ]:
#add the output layer
model.add(tf.keras.layers.Dense(units=1, activation='linear'))

In [ ]:
#Compilation
model.compile(optimizer = 'adam', loss ='mse', metrics = ['accuracy'])

In [ ]:
#Training, should not give a lot of epochs to a small dataset
history = model.fit(X_train, y_train, epochs = 100, verbose=2)

Epoch 1/100
13/13 - 0s - loss: 0.4119 - accuracy: 0.0000e+00 - 29ms/epoch - 2ms/step
Epoch 2/100
13/13 - 0s - loss: 0.4114 - accuracy: 0.0000e+00 - 28ms/epoch - 2ms/step
Epoch 3/100
13/13 - 0s - loss: 0.3949 - accuracy: 0.0000e+00 - 29ms/epoch - 2ms/step
Epoch 4/100
13/13 - 0s - loss: 0.3957 - accuracy: 0.0000e+00 - 30ms/epoch - 2ms/step
Epoch 5/100
13/13 - 0s - loss: 0.3813 - accuracy: 0.0000e+00 - 29ms/epoch - 2ms/step
Epoch 6/100
13/13 - 0s - loss: 0.3894 - accuracy: 0.0000e+00 - 42ms/epoch - 3ms/step
Epoch 7/100
13/13 - 0s - loss: 0.4036 - accuracy: 0.0000e+00 - 34ms/epoch - 3ms/step
Epoch 8/100
13/13 - 0s - loss: 0.4272 - accuracy: 0.0000e+00 - 28ms/epoch - 2ms/step
Epoch 9/100
13/13 - 0s - loss: 0.4217 - accuracy: 0.0000e+00 - 30ms/epoch - 2ms/step
Epoch 10/100
13/13 - 0s - loss: 0.3981 - accuracy: 0.0000e+00 - 34ms/epoch - 3ms/step
Epoch 11/100
13/13 - 0s - loss: 0.3846 - accuracy: 0.0000e+00 - 30ms/epoch - 2ms/step
Epoch 12/100
13/13 - 0s - loss: 0.4064 - accuracy: 0.0000e+00 - 29ms/epoch - 2ms/step
Epoch 13/100
13/13 - 0s - loss: 0.3858 - accuracy: 0.0000e+00 - 39ms/epoch - 3ms/step
Epoch 14/100
13/13 - 0s - loss: 0.3993 - accuracy: 0.0000e+00 - 28ms/epoch - 2ms/step
Epoch 15/100
13/13 - 0s - loss: 0.4088 - accuracy: 0.0000e+00 - 29ms/epoch - 2ms/step
Epoch 16/100
13/13 - 0s - loss: 0.3824 - accuracy: 0.0000e+00 - 41ms/epoch - 3ms/step
Epoch 17/100
13/13 - 0s - loss: 0.3992 - accuracy: 0.0000e+00 - 28ms/epoch - 2ms/step
Epoch 18/100
13/13 - 0s - loss: 0.4162 - accuracy: 0.0000e+00 - 33ms/epoch - 3ms/step
Epoch 19/100
13/13 - 0s - loss: 0.3817 - accuracy: 0.0000e+00 - 30ms/epoch - 2ms/step
Epoch 20/100
13/13 - 0s - loss: 0.3866 - accuracy: 0.0000e+00 - 32ms/epoch - 2ms/step
Epoch 21/100
13/13 - 0s - loss: 0.3833 - accuracy: 0.0000e+00 - 32ms/epoch - 2ms/step
Epoch 22/100
13/13 - 0s - loss: 0.3840 - accuracy: 0.0000e+00 - 29ms/epoch - 2ms/step
Epoch 23/100
13/13 - 0s - loss: 0.4286 - accuracy: 0.0000e+00 - 33ms/epoch - 3ms/step
Epoch 24/100
13/13 - 0s - loss: 0.4129 - accuracy: 0.0000e+00 - 28ms/epoch - 2ms/step
Epoch 25/100
13/13 - 0s - loss: 0.3727 - accuracy: 0.0000e+00 - 31ms/epoch - 2ms/step
Epoch 26/100
13/13 - 0s - loss: 0.3901 - accuracy: 0.0000e+00 - 37ms/epoch - 3ms/step
Epoch 27/100
13/13 - 0s - loss: 0.3802 - accuracy: 0.0000e+00 - 30ms/epoch - 2ms/step
Epoch 28/100
13/13 - 0s - loss: 0.3783 - accuracy: 0.0000e+00 - 29ms/epoch - 2ms/step
Epoch 29/100
13/13 - 0s - loss: 0.3937 - accuracy: 0.0000e+00 - 33ms/epoch - 3ms/step
Epoch 30/100
13/13 - 0s - loss: 0.3677 - accuracy: 0.0000e+00 - 28ms/epoch - 2ms/step
Epoch 31/100
13/13 - 0s - loss: 0.3746 - accuracy: 0.0000e+00 - 32ms/epoch - 2ms/step
Epoch 32/100
13/13 - 0s - loss: 0.4263 - accuracy: 0.0000e+00 - 36ms/epoch - 3ms/step
Epoch 33/100
13/13 - 0s - loss: 0.3838 - accuracy: 0.0000e+00 - 33ms/epoch - 3ms/step
Epoch 34/100
13/13 - 0s - loss: 0.4036 - accuracy: 0.0000e+00 - 42ms/epoch - 3ms/step
Epoch 35/100
13/13 - 0s - loss: 0.3726 - accuracy: 0.0000e+00 - 32ms/epoch - 2ms/step
Epoch 36/100
13/13 - 0s - loss: 0.3889 - accuracy: 0.0000e+00 - 30ms/epoch - 2ms/step
Epoch 37/100
13/13 - 0s - loss: 0.3990 - accuracy: 0.0000e+00 - 31ms/epoch - 2ms/step
Epoch 38/100
13/13 - 0s - loss: 0.3695 - accuracy: 0.0000e+00 - 31ms/epoch - 2ms/step
Epoch 39/100
13/13 - 0s - loss: 0.3820 - accuracy: 0.0000e+00 - 28ms/epoch - 2ms/step
Epoch 40/100
13/13 - 0s - loss: 0.3957 - accuracy: 0.0000e+00 - 33ms/epoch - 3ms/step
Epoch 41/100
13/13 - 0s - loss: 0.4321 - accuracy: 0.0000e+00 - 34ms/epoch - 3ms/step
Epoch 42/100
13/13 - 0s - loss: 0.3874 - accuracy: 0.0000e+00 - 28ms/epoch - 2ms/step
Epoch 43/100
13/13 - 0s - loss: 0.3701 - accuracy: 0.0000e+00 - 32ms/epoch - 2ms/step
Epoch 44/100
13/13 - 0s - loss: 0.3805 - accuracy: 0.0000e+00 - 31ms/epoch - 2ms/step
Epoch 45/100
13/13 - 0s - loss: 0.3885 - accuracy: 0.0000e+00 - 30ms/epoch - 2ms/step
Epoch 46/100
13/13 - 0s - loss: 0.3832 - accuracy: 0.0000e+00 - 32ms/epoch - 2ms/step
Epoch 47/100
13/13 - 0s - loss: 0.3771 - accuracy: 0.0000e+00 - 34ms/epoch - 3ms/step
Epoch 48/100
13/13 - 0s - loss: 0.3768 - accuracy: 0.0000e+00 - 30ms/epoch - 2ms/step
Epoch 49/100
13/13 - 0s - loss: 0.3742 - accuracy: 0.0000e+00 - 31ms/epoch - 2ms/step
Epoch 50/100
13/13 - 0s - loss: 0.3651 - accuracy: 0.0000e+00 - 31ms/epoch - 2ms/step
Epoch 51/100
13/13 - 0s - loss: 0.4072 - accuracy: 0.0000e+00 - 30ms/epoch - 2ms/step
Epoch 52/100
13/13 - 0s - loss: 0.3680 - accuracy: 0.0000e+00 - 29ms/epoch - 2ms/step
Epoch 53/100
13/13 - 0s - loss: 0.3694 - accuracy: 0.0000e+00 - 34ms/epoch - 3ms/step
Epoch 54/100
13/13 - 0s - loss: 0.3624 - accuracy: 0.0000e+00 - 31ms/epoch - 2ms/step
Epoch 55/100
13/13 - 0s - loss: 0.3638 - accuracy: 0.0000e+00 - 32ms/epoch - 2ms/step
Epoch 56/100
13/13 - 0s - loss: 0.3697 - accuracy: 0.0000e+00 - 32ms/epoch - 2ms/step
Epoch 57/100
13/13 - 0s - loss: 0.3754 - accuracy: 0.0000e+00 - 35ms/epoch - 3ms/step
Epoch 58/100
13/13 - 0s - loss: 0.4092 - accuracy: 0.0000e+00 - 29ms/epoch - 2ms/step
Epoch 59/100
13/13 - 0s - loss: 0.4029 - accuracy: 0.0000e+00 - 30ms/epoch - 2ms/step
Epoch 60/100
13/13 - 0s - loss: 0.4172 - accuracy: 0.0000e+00 - 33ms/epoch - 3ms/step
Epoch 61/100
13/13 - 0s - loss: 0.3654 - accuracy: 0.0000e+00 - 31ms/epoch - 2ms/step
Epoch 62/100
13/13 - 0s - loss: 0.3895 - accuracy: 0.0000e+00 - 31ms/epoch - 2ms/step
Epoch 63/100
13/13 - 0s - loss: 0.3926 - accuracy: 0.0000e+00 - 40ms/epoch - 3ms/step
Epoch 64/100
13/13 - 0s - loss: 0.3940 - accuracy: 0.0000e+00 - 31ms/epoch - 2ms/step
Epoch 65/100
13/13 - 0s - loss: 0.4145 - accuracy: 0.0000e+00 - 37ms/epoch - 3ms/step
Epoch 66/100
13/13 - 0s - loss: 0.3957 - accuracy: 0.0000e+00 - 31ms/epoch - 2ms/step
Epoch 67/100
13/13 - 0s - loss: 0.4066 - accuracy: 0.0000e+00 - 33ms/epoch - 3ms/step
Epoch 68/100
13/13 - 0s - loss: 0.3946 - accuracy: 0.0000e+00 - 29ms/epoch - 2ms/step
Epoch 69/100
13/13 - 0s - loss: 0.3853 - accuracy: 0.0000e+00 - 32ms/epoch - 2ms/step
Epoch 70/100
13/13 - 0s - loss: 0.3791 - accuracy: 0.0000e+00 - 29ms/epoch - 2ms/step
Epoch 71/100
13/13 - 0s - loss: 0.3981 - accuracy: 0.0000e+00 - 31ms/epoch - 2ms/step
Epoch 72/100
13/13 - 0s - loss: 0.3877 - accuracy: 0.0000e+00 - 35ms/epoch - 3ms/step
Epoch 73/100
13/13 - 0s - loss: 0.4052 - accuracy: 0.0000e+00 - 39ms/epoch - 3ms/step
Epoch 74/100
13/13 - 0s - loss: 0.4164 - accuracy: 0.0000e+00 - 31ms/epoch - 2ms/step
Epoch 75/100
13/13 - 0s - loss: 0.3796 - accuracy: 0.0000e+00 - 29ms/epoch - 2ms/step
Epoch 76/100
13/13 - 0s - loss: 0.3622 - accuracy: 0.0000e+00 - 32ms/epoch - 2ms/step
Epoch 77/100
13/13 - 0s - loss: 0.3791 - accuracy: 0.0000e+00 - 29ms/epoch - 2ms/step
Epoch 78/100
13/13 - 0s - loss: 0.3833 - accuracy: 0.0000e+00 - 38ms/epoch - 3ms/step
Epoch 79/100
13/13 - 0s - loss: 0.4007 - accuracy: 0.0000e+00 - 31ms/epoch - 2ms/step
Epoch 80/100
13/13 - 0s - loss: 0.4683 - accuracy: 0.0000e+00 - 29ms/epoch - 2ms/step
Epoch 81/100
13/13 - 0s - loss: 0.4818 - accuracy: 0.0000e+00 - 33ms/epoch - 3ms/step
Epoch 82/100
13/13 - 0s - loss: 0.5311 - accuracy: 0.0000e+00 - 35ms/epoch - 3ms/step
Epoch 83/100
13/13 - 0s - loss: 0.5618 - accuracy: 0.0000e+00 - 33ms/epoch - 3ms/step
Epoch 84/100
13/13 - 0s - loss: 0.4588 - accuracy: 0.0000e+00 - 38ms/epoch - 3ms/step
Epoch 85/100
13/13 - 0s - loss: 0.4806 - accuracy: 0.0000e+00 - 30ms/epoch - 2ms/step
Epoch 86/100
13/13 - 0s - loss: 0.4693 - accuracy: 0.0000e+00 - 32ms/epoch - 2ms/step
Epoch 87/100
13/13 - 0s - loss: 0.3761 - accuracy: 0.0000e+00 - 31ms/epoch - 2ms/step
Epoch 88/100
13/13 - 0s - loss: 0.4184 - accuracy: 0.0000e+00 - 30ms/epoch - 2ms/step
Epoch 89/100
13/13 - 0s - loss: 0.4132 - accuracy: 0.0000e+00 - 30ms/epoch - 2ms/step
Epoch 90/100
13/13 - 0s - loss: 0.4143 - accuracy: 0.0000e+00 - 42ms/epoch - 3ms/step
Epoch 91/100
13/13 - 0s - loss: 0.3798 - accuracy: 0.0000e+00 - 36ms/epoch - 3ms/step
Epoch 92/100
13/13 - 0s - loss: 0.3772 - accuracy: 0.0000e+00 - 33ms/epoch - 3ms/step
Epoch 93/100
13/13 - 0s - loss: 0.3766 - accuracy: 0.0000e+00 - 30ms/epoch - 2ms/step
Epoch 94/100
13/13 - 0s - loss: 0.4050 - accuracy: 0.0000e+00 - 32ms/epoch - 2ms/step
Epoch 95/100
13/13 - 0s - loss: 0.3533 - accuracy: 0.0000e+00 - 29ms/epoch - 2ms/step
Epoch 96/100
13/13 - 0s - loss: 0.3583 - accuracy: 0.0000e+00 - 35ms/epoch - 3ms/step
Epoch 97/100
13/13 - 0s - loss: 0.3830 - accuracy: 0.0000e+00 - 32ms/epoch - 2ms/step
Epoch 98/100
13/13 - 0s - loss: 0.4219 - accuracy: 0.0000e+00 - 36ms/epoch - 3ms/step
Epoch 99/100
13/13 - 0s - loss: 0.3806 - accuracy: 0.0000e+00 - 32ms/epoch - 2ms/step
Epoch 100/100
13/13 - 0s - loss: 0.3663 - accuracy: 0.0000e+00 - 32ms/epoch - 2ms/step

In [ ]:
#Evaluation
loss = model.evaluate(X_test, y_test)
loss

4/4 [==============================] - 0s 3ms/step - loss: 13.0555 - accuracy: 0.0000e+00

[13.05546760559082, 0.0]